### ISSUE TITLE
ping not working

### ISSUE THREAD

**Issue by dotIN** [jlaska/pytest-ansible#1] opened 2015-04-01 10:19 UTC
Hi,
      Was trying out this plugin , my ansible command works but my test fails with Error 'AnsibleHostUnreachable: Host unreachable' 

ansible -i hosts all -m ping -u <user_name> works 

```python
def test_ping(ansible_module):
    contacted = ansible_module.ping()
    for (host, result) in contacted.items():
        assert 'ping' in result, \
            "Failure on host:%s" % host
        assert result['ping'] == 'pong', \
            "Unexpected ping response: %s" % result['ping']
```

The above always fails , help appreciated

**Comment by jlaska** [comment] 2015-04-01 16:22
@dotIN Thanks for the report!  Can you include the `py.test` command-line and the traceback as well?

**Comment by dotIN** [comment] 2015-04-09 09:49
Ansible CLI 

ansible -i hosts all -u vagrant -m ping
192.168.33.10 | success >> {
    "changed": false,
    "ping": "pong"
}

py.test --ansible-host-pattern local --ansible-inventory hosts  --ansible-user vagrant test_ping.py
========================================================================================== test session starts ===========================================================================================
platform darwin -- Python 2.7.6 -- py-1.4.26 -- pytest-2.7.0
rootdir: /Users/py_test, inifile:
plugins: ansible
collected 1 items

test_ping.py F

================================================================================================ FAILURES ================================================================================================
_______________________________________________________________________________________________ test_ping ________________________________________________________________________________________________

ansible_module = <pytest_ansible.plugin.AnsibleModule object at 0x1028395d0>

    def test_ping(ansible_module):
>       contacted = ansible_module.ping()

test_ping.py:2:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <pytest_ansible.plugin.AnsibleModule object at 0x1028395d0>, args = (), kwargs = {'become': False, 'become_method': 'sudo', 'become_user': 'root', 'complex_args': {}, ...}, module_args = ''
hosts = ['192.168.33.10'], runner = <ansible.runner.Runner object at 0x102839950>
results = {'contacted': {}, 'dark': {'192.168.33.10': {'failed': True, 'msg': 'SSH Error: Permission denied (publickey,gssapi-ke...It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.'}}}

    def __run(self, *args, **kwargs):
        '''
            The API provided by ansible is not intended as a public API.
            '''

        # Assemble module argument string
        module_args = list()
        if args:
            module_args += list(args)
        module_args = ' '.join(module_args)

        # Assert hosts matching the provided pattern exist
        hosts = self.inventory_manager.list_hosts(self.pattern)
        if len(hosts) == 0:
            raise AnsibleNoHostsMatch("No hosts match:'%s'" % self.pattern)

        # Log the module and parameters
        log.debug("[%s] %s: %s, %s" % (self.pattern, self.module_name, module_args, kwargs))

        # Build module runner object
        kwargs = dict(
            inventory=self.inventory_manager,
            pattern=self.pattern,
            module_name=self.module_name,
            module_args=module_args,
            complex_args=kwargs,
            transport=self.options.get('connection'),
        )

        # Handle >= 1.9.0 options
        if has_ansible_become:
            kwargs.update(dict(
                become=self.options.get('become'),
                become_method=self.options.get('become_method'),
                become_user=self.options.get('become_user'),)
            )
        else:
            kwargs.update(dict(
                sudo=self.options.get('sudo'),
                sudo_user=self.options.get('sudo_user'),)
            )

        runner = ansible.runner.Runner(**kwargs)

        # Run the module
        results = runner.run()

        # FIXME - improve result output logging
        log.debug(results)

        # FIXME - should command failures raise an exception, or return?
        # If we choose to raise, callers will need to adapt accordingly
        # Catch any failures in the response
        # for host in results['contacted'].values():
        #     if 'failed' in host or host.get('rc', 0) != 0:
        #         raise Exception("Command failed: %s" % self.module_name, results)

        # Raise exception if host(s) unreachable
        # FIXME - if multiple hosts were involved, should an exception be raised?
        if results['dark']:
>           raise AnsibleHostUnreachable("Host unreachable", dark=results['dark'], contacted=results['contacted'])
E           AnsibleHostUnreachable: Host unreachable

n_py_test/lib/python2.7/site-packages/pytest_ansible/plugin.py:204: AnsibleHostUnreachable
======================================================================================== 1 failed in 0.12 seconds ========================================================================================

**Comment by jlaska** [comment] 2015-04-09 12:39
@dotIN can you share your inventory file please?  The `ansible` command you posted uses different parameters than the `py.test` command you've run.

For example, you are calling `ansible` using the host pattern `all`.  However, the `py.test` command is restricted to `local`.  Without access to your inventory file, it's unclear whether you have an inventory host named `local`.

**Comment by dotIN** [comment] 2015-04-10 01:39
cat hosts
[local]
192.168.33.10

**Comment by jlaska** [comment] 2015-04-10 02:12
I'm unable to reproduce the problem with the provided information.  The traceback provided is from `ansible` itself, not from the plugin code.  The traceback tells us ...

```
results = {'contacted': {}, 'dark': {'192.168.33.10': {'failed': True, 'msg': 'SSH Error: Permission denied (publickey,gssapi-ke...It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.'}}}
```

This means that ansible failed to connect to the host.  If you're interested in helping to debug further, you could modify the file `pytest_ansible/plugin.py` and uncomment the line:

```
ansible.utils.VERBOSITY = 4
```

This will increase the ansible debugging level and offer more detail as to why ssh is failing to connect.  Thanks!

**Comment by jlaska** [comment] 2015-04-20 18:29
`pytest-ansible-1.2.5` was just released.  It includes a fix for this issue, please retest and let me know if the problem remains.  Thanks!

**Closed by jlaska** 2015-04-20 18:29 UTC
